Repository forest-membership/non-block-king, pull requests merged in 2021-02, with the labels that each got.

#25 서버 측에 CI 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/node.js.yml
Labels: Setting ⚙️

#32 [FE] 컴포넌트 스토리북 작업 + 상태 분기처리
  client/src/@types/styled.d.ts
  client/src/components/atoms/Button/index.tsx
  client/src/components/atoms/Button/style.ts
  client/src/components/atoms/Input/index.stories.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Input/style.ts
  client/src/components/molecules/ModeSelectBox/index.stories.tsx
  client/src/components/molecules/ModeSelectBox/index.tsx
  client/src/components/molecules/ModeSelectBox/style.ts
  client/src/components/molecules/NicknameForm/index.stories.tsx
  client/src/components/molecules/NicknameForm/index.tsx
  client/src/pages/MainView/index.tsx
  client/src/pages/MainView/template/index.tsx
  client/src/pages/MainView/template/style.ts
  client/src/styles/theme.ts
Labels: FE 🖼

#30 [BE] 서버 측 테트리스 맵 로직
  server/package.json
  server/src/index.ts
  server/src/service/map/index.ts
  server/src/service/minos/I.mino.ts
  server/src/service/minos/J.mino.ts
  server/src/service/minos/L.mino.ts
  server/src/service/minos/O.mino.ts
  server/src/service/minos/S.mino.ts
  server/src/service/minos/T.mino.ts
  server/src/service/minos/Z.mino.ts
  server/src/service/minos/block/index.ts
  server/src/service/minos/index.ts
  server/src/service/minos/mino.ts
  server/src/service/minos/mino/index.ts
  server/src/service/status/index.ts
  server/src/types/position.ts
Labels: BE :back:, Code Style 🖌

#31 [BE] 닉네임 생성 API
  server/src/controllers/index.ts
  server/src/controllers/nickname.ts
  server/src/index.ts
  server/src/routers/index.ts
  server/src/routers/nickname.ts
  server/src/service/map/index.ts
  server/src/service/minos/index.ts
  server/src/service/nickname/adjective/index.ts
  server/src/service/nickname/index.ts
  server/src/service/nickname/noun/index.ts
Labels: BE :back:

#33 [FE, BE] 의존성 주입(DI) 및 닉네임 생성 API 연동
  client/src/apis/auth.ts
  client/src/apis/common/index.ts
  client/src/components/atoms/Input/index.tsx
  client/src/components/molecules/NicknameForm/index.tsx
  client/src/hooks/useAsync.ts
  client/src/pages/MainView/index.tsx
  client/src/pages/MainView/template/index.tsx
  server/.eslintrc.json
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/index.ts
  server/src/controllers/nickname.ts
  server/src/databases/redis/index.ts
  server/src/index.ts
  server/src/middlewares/express/index.ts
  server/src/middlewares/socket/index.ts
  server/src/models/map/index.ts
  server/src/routers/index.ts
  server/src/routers/nickname.ts
  server/src/routers/nickname/index.ts
  server/src/service/map/index.ts
  server/src/service/nickname/index.ts
  server/src/socker/index.ts
  server/src/sockets/gameManager/index.ts
  server/src/sockets/index.ts
  server/src/sockets/roomManager/index.ts
  server/src/types/position.ts
  server/src/utils/index.ts
  server/tsconfig.json
Labels: BE :back:, FE 🖼
